FROM nvidia/cuda:11.4.2-devel-ubuntu20.04

# Install dependencies
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y \
    --no-install-recommends \
    git \
    software-properties-common \
    yasm \
    python-setuptools \
    sudo \
    build-essential \
    python3 \
    python3-pip \
    wget

RUN python3 -m pip install distro meson ninja

# Build librist.
RUN git clone https://code.videolan.org/rist/librist.git
RUN cd librist && meson build && ninja -C build install

# Install golang.
RUN wget https://dl.google.com/go/go1.17.1.linux-amd64.tar.gz && tar -C /usr/local -xzf go1.17.1.linux-amd64.tar.gz && rm go1.17.1.linux-amd64.tar.gz
RUN ln -sf /usr/local/go/bin/go /usr/local/bin/go

# create the ubuntu user
RUN addgroup --system ubuntu \
    && adduser --system --shell /bin/bash --gecos 'ubuntu' \
       --uid 1005 --disabled-password --home /home/ubuntu ubuntu \
    && adduser ubuntu sudo \
    && echo ubuntu:ubuntu | chpasswd \
    && echo "ubuntu ALL=NOPASSWD:ALL" >> /etc/sudoers

RUN git clone https://gitlab.freedesktop.org/gstreamer/cerbero
RUN cd cerbero && git checkout 1.18.5

RUN chown -R ubuntu:ubuntu /cerbero

USER ubuntu

# Build gstreamer. 
RUN cd cerbero && ./cerbero-uninstalled bootstrap --assume-yes \
    && ./cerbero-uninstalled build gstreamer-1.0 \
    gst-plugins-base-1.0 \
    gst-plugins-good-1.0  \
    gst-plugins-bad-1.0 \
    gst-plugins-ugly-1.0 \
    gst-libav-1.0 \
    && rm -rf ./build/sources/*

USER root