FROM caddy:2-builder-alpine AS builder

RUN xcaddy build --with github.com/mholt/caddy-l4

FROM caddy:2-alpine

COPY --from=builder /usr/bin/caddy /usr/bin/caddy

COPY Caddyfile.json /etc/caddy/Caddyfile.json
COPY . /var/www/html